source 'https://github.com/CocoaPods/Specs.git'

# https://github.com/CocoaPods/CocoaPods/issues/4370
install! 'cocoapods', deterministic_uuids: false

use_frameworks!

target 'TAKKitSwiftSample' do
  pod "TAKKitSwift", :path => "../../"
end

target 'TAKKitSwiftSampleTests' do
  pod "TAKKitSwift", :path => "../../"
end
